modLoader="javafml"
# A version range to match for said mod loader - 45 is 1.19.4 or above
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/Tschipcraft/make_bubbles_pop/issues"
showAsResourcePack=false

[[mods]]
modId="make_bubbles_pop"
version="${file.jarVersion}-forge"
displayName="Make Bubbles Pop"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
updateJSONURL="https://api.modrinth.com/updates/gPCdW0Wr/forge_updates.json"
displayURL="https://github.com/Tschipcraft/make_bubbles_pop"
logoFile="assets/make_bubbles_pop/icon.png"
logoBlur=false
#credits="Thanks for this example mod goes to Java" #optional
authors="Tschipcraft"
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
displayTest="IGNORE_ALL_VERSION"

# The description text for the mod (multi line!) (#mandatory)
description='''
This client-side mod makes bubble particles pop and completely overhauls their behavior to make them rise realistically to the water surface.

It also adds bubble particles to opening chests and explosions underwater.
'''

[[dependencies.make_bubbles_pop]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="CLIENT"
